service:
  name: ${self:custom.NAME}

frameworkVersion: ">=1.27.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: ${self:custom.STAGE}
  profile: serverless-training

plugins:
  - serverless-prune-plugin
  # - serverless-plugin-warmup

custom:
  prune:
    automatic: true
    number: 1
  NAME: nuxt-on-lambda
  STAGE: ${file(./configs/env.js):exporter.STAGE}
  BASE_URL: ${file(./configs/env.js):exporter.BASE_URL}
  ENDPOINT_ENV: ${file(./configs/env.js):exporter.ENDPOINT_ENV}

package:
  exclude:
    - app/**

  include:
    - serverless.yml

functions:
  handler:
    handler: server/handler.handler
    # warmup: true
    timeout: 30
    memorySize: 128
    environment:
      BASE_URL: ${self:custom.BASE_URL}
      ENDPOINT_ENV: ${self:custom.ENDPOINT_ENV}
    events:
      - http:
          path: "/"
          method: get
      - http:
          path: "{proxy+}"
          method: get
